# Generated by Django 5.0.2 on 2024-02-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'managers', 'managed': True},
        ),
    ]
