# Generated by Django 5.0.2 on 2024-02-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'customuser_set', 'managed': True},
        ),
    ]
