# Generated by Django 5.0.2 on 2024-02-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_options_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'default_related_name': 'customuser_set', 'managed': True},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_healthcare_worker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
